import 'dart:async';
import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import '../services/app_state.dart';
import '../models/medicine.dart';
import 'add_medicine_screen.dart';
import 'sos_screen.dart';

const _healthTips = [
  "Take medicines at the same time every day — it helps build a routine your body can rely on.",
  "Store insulin and liquid medicines in the fridge, never the freezer.",
  "Drink a full glass of water with pills unless your doctor says otherwise.",
  "Low-salt meals go a long way in keeping blood pressure steady.",
  "A short 20-minute walk most days supports heart health.",
  "Keep a small note of any side effects to share at the next check-up.",
  "Never double up on a missed dose without checking with a doctor first.",
];

class HomeTab extends StatefulWidget {
  const HomeTab({super.key});

  @override
  State<HomeTab> createState() => _HomeTabState();
}

class _HomeTabState extends State<HomeTab> {
  int _tipIndex = 0;
  Timer? _tipTimer;
  final Set<String> _takenIds = {};

  @override
  void initState() {
    super.initState();
    _tipTimer = Timer.periodic(const Duration(seconds: 7), (_) {
      if (mounted) setState(() => _tipIndex = (_tipIndex + 1) % _healthTips.length);
    });
  }

  @override
  void dispose() {
    _tipTimer?.cancel();
    super.dispose();
  }

  int _sortValue(Medicine m) {
    final raw = m.doseTime;
    if (raw == null || !raw.contains(':')) return 9999;
    final parts = raw.split(':');
    return (int.tryParse(parts[0]) ?? 0) * 60 + (int.tryParse(parts[1]) ?? 0);
  }

  @override
  Widget build(BuildContext context) {
    final appState = context.watch<AppState>();
    final meds = [...appState.activeMedicines]..sort((a, b) => _sortValue(a).compareTo(_sortValue(b)));
    final isParent = appState.owner == 'parent';

    return RefreshIndicator(
      onRefresh: appState.refreshActiveMedicines,
      child: ListView(
        padding: const EdgeInsets.fromLTRB(20, 16, 20, 90),
        children: [
          if (isParent)
            Padding(
              padding: const EdgeInsets.only(bottom: 16),
              child: SizedBox(
                width: double.infinity,
                child: ElevatedButton.icon(
                  style: ElevatedButton.styleFrom(backgroundColor: const Color(0xFFD1382B), padding: const EdgeInsets.symmetric(vertical: 14)),
                  icon: const Icon(Icons.warning_amber_rounded),
                  label: Text("SOS — Call ${appState.parentProfile?.fullName ?? 'their'} guardian"),
                  onPressed: () => Navigator.of(context).push(
                    MaterialPageRoute(
                      builder: (_) => SosScreen(
                        profile: appState.parentProfile!,
                        ownerId: appState.selfProfile!.id,
                      ),
                    ),
                  ),
                ),
              ),
            ),
          Card(
            color: Theme.of(context).colorScheme.errorContainer.withOpacity(0.25),
            child: Padding(
              padding: const EdgeInsets.all(16),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  const Text('❤️ Health Tip of the Day', style: TextStyle(fontWeight: FontWeight.bold)),
                  const SizedBox(height: 6),
                  Text(_healthTips[_tipIndex]),
                ],
              ),
            ),
          ),
          const SizedBox(height: 16),
          if (appState.activeProfile?.careTips != null) ...[
            Card(
              child: Padding(
                padding: const EdgeInsets.all(16),
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Row(
                      children: [
                        Icon(Icons.auto_awesome, size: 16, color: Theme.of(context).colorScheme.primary),
                        const SizedBox(width: 6),
                        const Text('Things to be mindful of', style: TextStyle(fontWeight: FontWeight.bold)),
                      ],
                    ),
                    const SizedBox(height: 8),
                    Text(appState.activeProfile!.careTips!, style: const TextStyle(fontSize: 13)),
                    const SizedBox(height: 10),
                    Container(
                      padding: const EdgeInsets.all(8),
                      decoration: BoxDecoration(
                        color: Theme.of(context).colorScheme.surfaceContainerHighest,
                        borderRadius: BorderRadius.circular(8),
                      ),
                      child: Text(
                        'Generated by AI based on the medicines you\'ve added. This is general information only — not a diagnosis, and not a substitute for advice from a doctor or pharmacist.',
                        style: TextStyle(fontSize: 10.5, color: Theme.of(context).colorScheme.onSurfaceVariant),
                      ),
                    ),
                  ],
                ),
              ),
            ),
            const SizedBox(height: 16),
          ],
          Text("Today's Schedule", style: Theme.of(context).textTheme.labelLarge),
          const SizedBox(height: 8),
          if (meds.isEmpty)
            const Card(
              child: Padding(
                padding: EdgeInsets.all(24),
                child: Center(child: Text('No medicines today', style: TextStyle(fontWeight: FontWeight.bold))),
              ),
            )
          else
            ...meds.map((m) {
              final taken = _takenIds.contains(m.id);
              return Card(
                child: ListTile(
                  leading: Icon(taken ? Icons.check_circle : Icons.circle_outlined,
                      color: taken ? Theme.of(context).colorScheme.primary : null),
                  title: Text('${m.displayTime} · ${m.name}', style: TextStyle(decoration: taken ? TextDecoration.lineThrough : null)),
                  onTap: () => setState(() {
                    taken ? _takenIds.remove(m.id) : _takenIds.add(m.id);
                  }),
                ),
              );
            }),
          if (meds.isNotEmpty) ...[
            const SizedBox(height: 16),
            Text('Tomorrow', style: Theme.of(context).textTheme.labelLarge),
            const SizedBox(height: 8),
            ...meds.map((m) => ListTile(
                  dense: true,
                  leading: const Icon(Icons.alarm, size: 18),
                  title: Text('${m.displayTime}  ${m.name}'),
                )),
          ],
          const SizedBox(height: 16),
          ElevatedButton.icon(
            icon: const Icon(Icons.add),
            label: const Text('Add a med'),
            onPressed: () => Navigator.of(context).push(
              MaterialPageRoute(builder: (_) => const AddMedicineScreen()),
            ),
          ),
        ],
      ),
    );
  }
}
